# Config file where you can blacklist certain IPs/networks
# or specify certain networks

# LAST UPDATED FOR UB

valid:
  - default # This will pull the network and netmask from the default gateway

invalid: