version: '3'
services:
    crowdcontrol:
        build: images/crowdcontrol/
        environment:
            - "PWNBOARD_URL=${PWNBOARD_URL}:${PWNBOARD_PORT}/generic"
            - FLASK_DEBUG=False

    spin:
        build: https://github.com/degenerat3/javascript-winwheel.git
 
    pwnboard:
        build: https://github.com/micahjmartin/pwnboard.git
        environment:
            - FLASK_DEBUG=false
            - FLASK_PORT=5000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - "PWNBOARD_URL=${PWNBOARD_URL}"
            - "SYSLOG_HOST=${SAWMILL_HOST}"
            - "SYSLOG_PORT=${SAWMILL_PORT}"
            - CACHE_TIME=-1
            - HOST_TIMEOUT=3
        volumes:
            - ./images/pwnboard/board.json:/opt/pwnboard/board.json:ro
    
    # Required for the pwnboard
    redis:
        image: redis:alpine
        restart: always

    # Forwards all the different domains to the correct server
    # See nginx.conf to modify the behavior
    proxy:
        build: images/proxy/
        ports:
            - 80:80
        volumes:
            # List all the servers that we want to proxy here
            - ./images/proxy/servers/crowdcontrol.conf:/etc/nginx/conf.d/cc.conf:ro
            - ./images/proxy/servers/pwnboard.conf:/etc/nginx/conf.d/pwnboard.conf:ro
            - ./images/proxy/servers/spin.conf:/etc/nginx/conf.d/spin.conf:ro
