version: '3'
services:
    halo_crowdcontrol:
        build: https://github.com/RITRedteam/TheArkHalo.git
        network_mode: 'host'
        privileged: true
        environment:  
            # Halo settings
            - HALO_NAME=CrowdControl
            - HALO_UPSTREAM=http://cc.c2the.world
            # The number of IPs to use for this service
            - HALO_ADDR_COUNT=20
    
            # If the proxy needs to add a host header, use this value
            - PROXY_HOST=cc.c2the.world

            - THEARK_SERVER=http://${ARK_HOST}:${ARK_PORT}
            - THEARK_USER=${REDTEAM_USER}
            - THEARK_PASS=${REDTEAM_PASS}
            - THEARK_REGISTER=True
    
    halo_chainsaw:
        build: https://github.com/RITRedteam/TheArkHalo.git
        network_mode: 'host'
        privileged: true
        environment:  
            # Halo settings
            - HALO_NAME=Chainsaw
            - HALO_UPSTREAM=http://chainsaw.c2the.world
            # The number of IPs to use for this service
            - HALO_ADDR_COUNT=20
    
            # If the proxy needs to add a host header, use this value
            - PROXY_HOST=chainsaw.c2the.world

            - THEARK_SERVER=http://${ARK_HOST}:${ARK_PORT}
            - THEARK_USER=${REDTEAM_USER}
            - THEARK_PASS=${REDTEAM_PASS}
            - THEARK_REGISTER=True

    halo_sovereignty:
        build: https://github.com/RITRedteam/TheArkHalo.git
        network_mode: 'host'
        privileged: true
        environment:  
            # Halo settings
            - HALO_NAME=Sovereignty
            - HALO_UPSTREAM=http://ssh.bullecoin.com
            # The number of IPs to use for this service
            - HALO_ADDR_COUNT=20

            - THEARK_SERVER=http://${ARK_HOST}:${ARK_PORT}
            - THEARK_USER=${REDTEAM_USER}
            - THEARK_PASS=${REDTEAM_PASS}
            - THEARK_REGISTER=True

    halo_meteor:
        build: https://github.com/RITRedteam/TheArkHalo.git
        network_mode: 'host'
        privileged: true
        environment:  
            # Halo settings
            - HALO_NAME=Meteor
            - HALO_UPSTREAM=http://pwnyour.systems
            # The number of IPs to use for this service
            - HALO_ADDR_COUNT=20
    
            - THEARK_SERVER=http://${ARK_HOST}:${ARK_PORT}
            - THEARK_USER=${REDTEAM_USER}
            - THEARK_PASS=${REDTEAM_PASS}
            - THEARK_REGISTER=True