version: '3'
services:
    halo_crowdcontrol:
        build: https://github.com/RITRedteam/TheArkHalo.git
        network_mode: 'host'
        privileged: true
        environment:  
            # Halo settings
            - HALO_NAME=CrowdControl
            - HALO_UPSTEAM=http://cc.c2the.world
            # The number of IPs to use for this service
            - HALO_ADDR_COUNT=15

            - THEARK_SERVER=http://${ARK_HOST}:${ARK_PORT}
            - THEARK_USER=${REDTEAM_USER}
            - THEARK_PASS=${REDTEAM_PASS}
            - THEARK_REGISTER=True