version: '3'
services:
    theark:
        build: https://github.com/ritredteam/theark.git
        network_mode: 'host'
        privileged: true
        environment:
            - FLASK_HOST=${ARK_HOST}
            - FLASK_DEBUG=false
            - FLASK_PORT=80
            - ARK_DATABASE=./db/theark.sqlite
            - ARK_CONFIG=./db/config.yml
        volumes:
            - ./images/theark:/opt/theark/db/:rw
        healthcheck:
            test: ["CMD", "curl", "-f", "http://${ARK_HOST}"]
            interval: '10s'
            timeout: '10s'
            retries: 5
    sangheili:
        build: 'images/sangheili/'
        network_mode: 'host'
        privileged: true
        environment:
            - address_server=http://${ARK_HOST}
            - reserve_addresses=True
            - address_count=20
        restart: on-failure
        depends_on:
            - theark